url: http://blog.nancheung.com

##七牛云的key
qiniu:
  accessKey: 
  secretKey: 
  bucketName: 
  basePath: 

## 百度推送
baidu:
  task:
    postUrl: 
    baseUrl:

#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: 
  thymeleaf:
    mode: HTML5
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: nanCheung-blog

#mynatis配置
mybatis:
  type-aliases-package: com.blog.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml

#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file:

#服务配置
server:
  session:
    timeout: 172800
  port: 8080





